apiVersion: v1 
kind: Pod 
metadata:
  name: spring-pod
  namespace: springns
  labels: 
    app: spring 
    env: dev 
spec: 
  containers: 
  - image: 489064644984.dkr.ecr.us-east-1.amazonaws.com/dockercicdk8:2
    name: spring-con 
    ports:
    - containerPort: 8080
      protocol: TCP     